import { MESSAGES } from '../data/messages';

function toCSharpFilterArgs(m: (typeof MESSAGES)[0]): string {
  const cx = m.contextMatch;
  if (!cx) return 'null';
  const parts: string[] = [];
  if (cx.prevFrameResult !== undefined) parts.push(`PrevFrameResult = ${cx.prevFrameResult === null ? 'null' : `"${cx.prevFrameResult}"`}`);
  if (cx.hasHadStrike !== undefined) parts.push(`HasHadStrike = ${cx.hasHadStrike}`);
  if (cx.hasHadSpare !== undefined) parts.push(`HasHadSpare = ${cx.hasHadSpare}`);
  if (cx.phase !== undefined) parts.push(`Phase = "${cx.phase}"`);
  if (cx.pinsFirstThrowMin !== undefined) parts.push(`PinsFirstThrowMin = ${cx.pinsFirstThrowMin}`);
  if (cx.pinsFirstThrowMax !== undefined) parts.push(`PinsFirstThrowMax = ${cx.pinsFirstThrowMax}`);
  return `new ContextFilter { ${parts.join(', ')} }`;
}

export function generateCSharp(): string {
  const eventTypes = [...new Set(MESSAGES.map(m => m.eventType))];

  const enumValues = eventTypes.map(e => `    ${e},`).join('\n');

  const messageEntries = MESSAGES.map(m =>
    `        new BowlingMessage("${m.id}", EventType.${m.eventType}, ${m.variant}, MessageVoice.${m.voice.charAt(0).toUpperCase() + m.voice.slice(1)}, @"${m.text.replace(/"/g, '""')}", ${toCSharpFilterArgs(m)})`
  ).join(',\n');

  return `// Auto-generated by Bowling Plus Simulator
// Do not edit manually — regenerate from the simulator

using System.Collections.Generic;
using System.Linq;

namespace BowlingPlus
{
    public enum EventType
    {
${enumValues}
    }

    public enum MessageVoice
    {
        Reactive,
        Encouraging,
        Educational
    }

    public class ContextFilter
    {
        public string PrevFrameResult;
        public bool? HasHadStrike;
        public bool? HasHadSpare;
        public string Phase;
        public int? PinsFirstThrowMin;
        public int? PinsFirstThrowMax;

        public bool Matches(string prevFrameResult, bool hasHadStrike, bool hasHadSpare, string phase, int pinsFirstThrow)
        {
            if (PrevFrameResult != null && PrevFrameResult != prevFrameResult) return false;
            if (HasHadStrike.HasValue && HasHadStrike.Value != hasHadStrike) return false;
            if (HasHadSpare.HasValue && HasHadSpare.Value != hasHadSpare) return false;
            if (Phase != null && Phase != phase) return false;
            if (PinsFirstThrowMin.HasValue && pinsFirstThrow < PinsFirstThrowMin.Value) return false;
            if (PinsFirstThrowMax.HasValue && pinsFirstThrow > PinsFirstThrowMax.Value) return false;
            return true;
        }
    }

    [System.Serializable]
    public class BowlingMessage
    {
        public string Id;
        public EventType Event;
        public int Variant;
        public MessageVoice Voice;
        public string Text;
        public ContextFilter Filter;

        public BowlingMessage(string id, EventType evt, int variant, MessageVoice voice, string text, ContextFilter filter = null)
        {
            Id = id;
            Event = evt;
            Variant = variant;
            Voice = voice;
            Text = text;
            Filter = filter;
        }
    }

    public static class BowlingMessageDatabase
    {
        private static readonly Dictionary<string, int> _counters = new Dictionary<string, int>();

        public static readonly List<BowlingMessage> All = new List<BowlingMessage>
        {
${messageEntries}
        };

        public static BowlingMessage SelectMessage(EventType eventType, string prevFrameResult = null, bool hasHadStrike = false, bool hasHadSpare = false, string phase = null, int pinsFirstThrow = 0)
        {
            var contextPool = All.Where(m => m.Event == eventType && m.Filter != null &&
                m.Filter.Matches(prevFrameResult, hasHadStrike, hasHadSpare, phase, pinsFirstThrow)).ToList();
            var defaultPool = All.Where(m => m.Event == eventType && m.Filter == null).ToList();

            var pool = contextPool.Count > 0 ? contextPool : defaultPool;
            if (pool.Count == 0) return null;

            var counterKey = contextPool.Count > 0 ? $"{eventType}:ctx" : eventType.ToString();
            if (!_counters.ContainsKey(counterKey)) _counters[counterKey] = 0;
            var msg = pool[_counters[counterKey] % pool.Count];
            _counters[counterKey]++;
            return msg;
        }

        public static void ResetCounters() => _counters.Clear();
    }

    public static class BowlingScoring
    {
        public static int[] CalculateFrameScores(int[] throws)
        {
            var scores = new int?[10];
            int i = 0;

            for (int f = 0; f < 10; f++)
            {
                if (i >= throws.Length) break;

                if (f == 9)
                {
                    int t1 = i < throws.Length ? throws[i] : -1;
                    int t2 = i + 1 < throws.Length ? throws[i + 1] : -1;
                    int t3 = i + 2 < throws.Length ? throws[i + 2] : -1;
                    if (t1 == -1) break;
                    if (t1 == 10) { if (t2 == -1 || t3 == -1) break; scores[9] = t1 + t2 + t3; }
                    else if (t2 != -1 && t1 + t2 == 10) { if (t3 == -1) break; scores[9] = t1 + t2 + t3; }
                    else { if (t2 == -1) break; scores[9] = t1 + t2; }
                }
                else if (throws[i] == 10)
                {
                    if (i + 2 >= throws.Length) break;
                    scores[f] = 10 + throws[i + 1] + throws[i + 2];
                    i++; continue;
                }
                else
                {
                    if (i + 1 >= throws.Length) break;
                    int t1 = throws[i], t2 = throws[i + 1];
                    if (t1 + t2 == 10) { if (i + 2 >= throws.Length) break; scores[f] = 10 + throws[i + 2]; }
                    else scores[f] = t1 + t2;
                    i += 2; continue;
                }
                i++;
            }

            var result = new int[10];
            for (int f = 0; f < 10; f++) result[f] = scores[f] ?? 0;
            return result;
        }

        public static int[] GetCumulativeScores(int[] frameScores)
        {
            var cumulative = new int[10];
            int total = 0;
            for (int f = 0; f < 10; f++) { total += frameScores[f]; cumulative[f] = total; }
            return cumulative;
        }
    }
}
`;
}
