import { MESSAGES } from '../data/messages';

export function generateCSharp(): string {
  const eventTypes = [...new Set(MESSAGES.map(m => m.eventType))];

  const enumValues = eventTypes.map(e => `    ${e},`).join('\n');

  const messageEntries = MESSAGES.map(m =>
    `        new BowlingMessage("${m.id}", EventType.${m.eventType}, ${m.variant}, MessageVoice.${m.voice.charAt(0).toUpperCase() + m.voice.slice(1)}, @"${m.text.replace(/"/g, '""')}")`
  ).join(',\n');

  return `// Auto-generated by Bowling Plus Simulator
// Do not edit manually — regenerate from the simulator

using System.Collections.Generic;
using System.Linq;

namespace BowlingPlus
{
    public enum EventType
    {
${enumValues}
    }

    public enum MessageVoice
    {
        Reactive,
        Encouraging,
        Educational
    }

    [System.Serializable]
    public class BowlingMessage
    {
        public string Id;
        public EventType Event;
        public int Variant;
        public MessageVoice Voice;
        public string Text;

        public BowlingMessage(string id, EventType evt, int variant, MessageVoice voice, string text)
        {
            Id = id;
            Event = evt;
            Variant = variant;
            Voice = voice;
            Text = text;
        }
    }

    public static class BowlingMessageDatabase
    {
        private static readonly Dictionary<EventType, int> _counters = new Dictionary<EventType, int>();

        public static readonly List<BowlingMessage> All = new List<BowlingMessage>
        {
${messageEntries}
        };

        public static BowlingMessage SelectMessage(EventType eventType)
        {
            var pool = All.Where(m => m.Event == eventType).ToList();
            if (pool.Count == 0) return null;

            if (!_counters.ContainsKey(eventType)) _counters[eventType] = 0;
            var msg = pool[_counters[eventType] % pool.Count];
            _counters[eventType]++;
            return msg;
        }

        public static void ResetCounters() => _counters.Clear();
    }

    public static class BowlingScoring
    {
        public static int[] CalculateFrameScores(int[] throws)
        {
            var scores = new int?[10];
            int i = 0;

            for (int f = 0; f < 10; f++)
            {
                if (i >= throws.Length) break;

                if (f == 9)
                {
                    int t1 = i < throws.Length ? throws[i] : -1;
                    int t2 = i + 1 < throws.Length ? throws[i + 1] : -1;
                    int t3 = i + 2 < throws.Length ? throws[i + 2] : -1;
                    if (t1 == -1) break;
                    if (t1 == 10) { if (t2 == -1 || t3 == -1) break; scores[9] = t1 + t2 + t3; }
                    else if (t2 != -1 && t1 + t2 == 10) { if (t3 == -1) break; scores[9] = t1 + t2 + t3; }
                    else { if (t2 == -1) break; scores[9] = t1 + t2; }
                }
                else if (throws[i] == 10)
                {
                    if (i + 2 >= throws.Length) break;
                    scores[f] = 10 + throws[i + 1] + throws[i + 2];
                    i++; continue;
                }
                else
                {
                    if (i + 1 >= throws.Length) break;
                    int t1 = throws[i], t2 = throws[i + 1];
                    if (t1 + t2 == 10) { if (i + 2 >= throws.Length) break; scores[f] = 10 + throws[i + 2]; }
                    else scores[f] = t1 + t2;
                    i += 2; continue;
                }
                i++;
            }

            var result = new int[10];
            for (int f = 0; f < 10; f++) result[f] = scores[f] ?? 0;
            return result;
        }

        public static int[] GetCumulativeScores(int[] frameScores)
        {
            var cumulative = new int[10];
            int total = 0;
            for (int f = 0; f < 10; f++) { total += frameScores[f]; cumulative[f] = total; }
            return cumulative;
        }
    }
}
`;
}
